### ISSUE TITLE
How to use Yewprint NumericInput

### ISSUE THREAD

**Issue by cecton** [yewprint/yewprint#128]
> Dear Cecile,
>
> I would like to thank you for the work you have done on Yewprint; it is wonderful. I have been playing around with some examples and have become a bit confused about NumericInput. **How do you get the value that the user has input so that it can be used elsewhere? I have tried using a callback with the onchange property but I can't get it to work.** If you could point me in the right direction or to a relevant example I would be really grateful.
>
> Kind regards,

Hey @yozhgoor :wave: I got this email today and I thought it would be a good exercise for you.

I labelled it as a question as it came as a question to me but feel free to analyze, update the ticket and answer here and I will transmit to the original author.

Don't hesitate to come back to me if you have any question.

**Comment by yozhgoor** [comment]
My bad, the `onchange` prop is defined in the struct, but isn't in the code itself.
I can fix that along with the fact that you can't access to the source code from the doc

**Comment by yozhgoor** [comment]
Fixed with #129
