### ISSUE TITLE
Request for Numeric Input and Tabs

### ISSUE THREAD

**Issue by fredfortier** [yewprint/yewprint#57]
Good job so far! It would be great to get Numeric Input and Tabs next.

 - [x] Tabs
 - [x] Numeric input

**Comment by cecton** [comment]
Tabs: https://yewprint.rm.rs/#tabs

**Comment by yozhgoor** [comment]
NumericInput: https://yewprint.rm.rs/#numeric-input

**Comment by cecton** [comment]
Ah nothing else to do then? I'll close the PR but feel free to re-open if something's still missing
